#!/usr/bin/env bash

set -euo pipefail

[ "${BASH_VERSINFO:-0}" -ge 4 ] || {
  echo "bash version 4 or higher is required" >&2
  exit 1
}

build() {
  docker build \
    -f traefik/Dockerfile \
    -t octomation/stub:latest \
    traefik
}

publish() {
  docker buildx build \
    --platform linux/amd64,linux/arm64 \
    --push \
    -f traefik/Dockerfile \
    -t ghcr.io/octomation/stub:latest \
    traefik
}

server() {
  docker run \
    --rm -it \
    -v "$(pwd)/traefik/users":/runtime/users \
    octomation/stub:latest
}

"${@}"
