#!/usr/bin/env bash

set -euo pipefail

[ "${BASH_VERSINFO:-0}" -ge 4 ] || {
  echo "bash version 4 or higher is required" >&2
  exit 1
}

publish() {
  docker buildx build \
    --platform linux/amd64,linux/arm64 \
    --push \
    -f Dockerfile \
    -t ghcr.io/octomation/stub:latest \
    .
}

"${@}"
