// Code generated by github.com/kamilsk/egg. DO NOT EDIT.

//go:build tools

package tools

import _ "github.com/otto-de/traefik-config-validator/cmd/traefik-config-validator"

//go:generate go install github.com/otto-de/traefik-config-validator/cmd/traefik-config-validator
